name: ci-jdk8
on:
  push:
    branches: ['main']
    paths:
      - 'zulu-openjdk/8/**'
jobs:
  BuildX:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    env:
      ALPINE_VER: '3.19'
      REGISTRY: ghcr.io
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push "zulu-openjdk-8-lts"
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: ./zulu-openjdk/8/8u442/alpine
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/zulu-openjdk:8u442-alpine${{ env.ALPINE_VER }}